package com.example.dreamybloomapp.ui.theme

import androidx.compose.ui.graphics.Color

//light color
val primaryLight = Color(0xFF834C75)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD7F0)
val onPrimaryContainerLight = Color(0xFF68355C)
val secondaryLight = Color(0xFF894A67)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD8E6)
val onSecondaryContainerLight = Color(0xFF6E334F)
val tertiaryLight = Color(0xFF894A68)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8E6)
val onTertiaryContainerLight = Color(0xFF6D3350)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF73332D)
val backgroundLight = Color(0xFFFFF7F9)
val onBackgroundLight = Color(0xFF201A1E)
val surfaceLight = Color(0xFFFFF7F9)
val onSurfaceLight = Color(0xFF201A1E)
val surfaceVariantLight = Color(0xFFEFDEE6)
val onSurfaceVariantLight = Color(0xFF4F444A)
val outlineLight = Color(0xFF80737B)
val outlineVariantLight = Color(0xFFD2C2CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362E33)
val inverseOnSurfaceLight = Color(0xFFFBEDF3)
val inversePrimaryLight = Color(0xFFF5B2E1)
val surfaceDimLight = Color(0xFFE4D7DC)
val surfaceBrightLight = Color(0xFFFFF7F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFEF0F6)
val surfaceContainerLight = Color(0xFFF8EAF0)
val surfaceContainerHighLight = Color(0xFFF2E5EA)
val surfaceContainerHighestLight = Color(0xFFECDFE5)

//Dark colors
val primaryLightMediumContrast = Color(0xFF55244B)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF935A84)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF5A233E)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF9A5976)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF5A233F)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9A5977)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF5E231E)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFA25851)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7F9)
val onBackgroundLightMediumContrast = Color(0xFF201A1E)
val surfaceLightMediumContrast = Color(0xFFFFF7F9)
val onSurfaceLightMediumContrast = Color(0xFF150F13)
val surfaceVariantLightMediumContrast = Color(0xFFEFDEE6)
val onSurfaceVariantLightMediumContrast = Color(0xFF3D3339)
val outlineLightMediumContrast = Color(0xFF5B4F56)
val outlineVariantLightMediumContrast = Color(0xFF766A71)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF362E33)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFBEDF3)
val inversePrimaryLightMediumContrast = Color(0xFFF5B2E1)
val surfaceDimLightMediumContrast = Color(0xFFD0C3C9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF7F9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFEF0F6)
val surfaceContainerLightMediumContrast = Color(0xFFF2E5EA)
val surfaceContainerHighLightMediumContrast = Color(0xFFE6D9DF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDBCED4)




