package com.example.dreamybloomapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light colors
val primaryLight = Color(0xFF834C75)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD7F0)
val onPrimaryContainerLight = Color(0xFF68355C)
val secondaryLight = Color(0xFF894A67)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD8E6)
val onSecondaryContainerLight = Color(0xFF6E334F)
val tertiaryLight = Color(0xFF894A68)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8E6)
val onTertiaryContainerLight = Color(0xFF6D3350)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF73332D)
val backgroundLight = Color(0xFFFFF7F9)
val onBackgroundLight = Color(0xFF201A1E)
val surfaceLight = Color(0xFFFFF7F9)
val onSurfaceLight = Color(0xFF201A1E)
val surfaceVariantLight = Color(0xFFEFDEE6)
val onSurfaceVariantLight = Color(0xFF4F444A)
val outlineLight = Color(0xFF80737B)
val outlineVariantLight = Color(0xFFD2C2CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362E33)
val inverseOnSurfaceLight = Color(0xFFFBEDF3)
val inversePrimaryLight = Color(0xFFF5B2E1)
val surfaceDimLight = Color(0xFFE4D7DC)
val surfaceBrightLight = Color(0xFFFFF7F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFEF0F6)
val surfaceContainerLight = Color(0xFFF8EAF0)
val surfaceContainerHighLight = Color(0xFFF2E5EA)
val surfaceContainerHighestLight = Color(0xFFECDFE5)

// Dark colors - These are the standard colors used by the darkColorScheme
val primaryDark = Color(0xFFF5B2E1)
val onPrimaryDark = Color(0xFF4E1E44)
val primaryContainerDark = Color(0xFF68355C)
val onPrimaryContainerDark = Color(0xFFFFD7F0)
val secondaryDark = Color(0xFFFFB0D1)
val onSecondaryDark = Color(0xFF531D38)
val secondaryContainerDark = Color(0xFF6E334F)
val onSecondaryContainerDark = Color(0xFFFFD8E6)
val tertiaryDark = Color(0xFFFEB0D2)
val onTertiaryDark = Color(0xFF531D39)
val tertiaryContainerDark = Color(0xFF6D3350)
val onTertiaryContainerDark = Color(0xFFFFD8E6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73332D)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF181215)
val onBackgroundDark = Color(0xFFECDFE5)
val surfaceDark = Color(0xFF181215)
val onSurfaceDark = Color(0xFFECDFE5)
val surfaceVariantDark = Color(0xFF4F444A)
val onSurfaceVariantDark = Color(0xFFD2C2CA)
val outlineDark = Color(0xFF9B8D94)
val outlineVariantDark = Color(0xFF4F444A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFECDFE5)
val inverseOnSurfaceDark = Color(0xFF362E33)
val inversePrimaryDark = Color(0xFF834C75)
val surfaceDimDark = Color(0xFF181215)
val surfaceBrightDark = Color(0xFF3F373B)
val surfaceContainerLowestDark = Color(0xFF120C10)
val surfaceContainerLowDark = Color(0xFF201A1E)
val surfaceContainerDark = Color(0xFF241E22)
val surfaceContainerHighDark = Color(0xFF2F282C)
val surfaceContainerHighestDark = Color(0xFF3A3337)

// NOTE: We are intentionally excluding the Medium and High contrast colors
// (e.g., *MediumContrast and *HighContrast) from this file's code block for
// clarity, as they are not used in the standard DarkColorScheme in Theme.kt.
// However, if you included them in your local file, it's fine.
